import "./table.css"
import ServiceInvoice from "./ServiceInvoice";
import { useState } from "react";

const Table = ({ data, query, error }) => {
    const [pid, setPid] = useState('')//this is id generated by db for every record
    const [name, setName] = useState('')
    const [modalOpen, setModalOpen] = useState(false);
    function openInvoice(Pid, clientName){
      setModalOpen(true)
      setPid(Pid)
      setName(clientName)
    }
    return (
      <div className="recordsTableContainer">
            {data.length ? <table className="staffRecordsTable">
                <thead className="staffTHead">
                    <tr>
                        <th>ID</th>
                        <th>Client name</th>
                        <th>Requested by</th>
                        <th>Scope</th>
                        <th>Work location</th>
                    </tr>
                </thead>
                <tbody className="staffTBody">
                    {data.filter((name)=>{
                      return query === '' ? name : name.client_name.toLowerCase().includes(query) || name.requested_by.toLowerCase().includes(query);
                    })
                    .map((item,idx) => (
                    <tr key={item._id} onClick={()=>openInvoice(item.payment_details, item.client_name)}>
                      <td>{idx}</td>
                      <td>{item.client_name}</td>
                      <td>{item.requested_by}</td>
                      <td>{item.scope}</td>
                      <td>{item.work_location}</td>
                    </tr>
                ))}
                </tbody> 
            </table>: <p>{error}</p> }
          {modalOpen &&
          <ServiceInvoice 
            pid={pid} name={name}
            closeModal={() => {
              setModalOpen(false);
            }}
          />}
      </div>
    );
  };
  
  export default Table;